### ISSUE TITLE
listen unix /run/user/0/sia-nbdserver: bind: permission denied

### ISSUE THREAD

**Issue by arko36** [javgh/sia-nbdserver#2]
I can not get the nbd sia server to work. this is the message

2020/07/02 20:53:45 Storing cache in /home/myuser/.local/share/sia-nbdserver
2020/07/02 20:53:45 listen unix /run/myuser/0/sia-nbdserver: bind: permission denied

Thanks

**Comment by javgh** [comment]
The server tries to create a unix socket at /run/myuser/0/sia-nbdserver . That path needs to be writeable. Probably this is a bad default for your system. You can set a different path using the `-u` flag, so for example: `sia-nbdserver -u /tmp/sia-nbdserver.sock`. Then make sure to pass the same path to `nbd-client` - it also accepts a `-u` flag. Hope that helps!
