### ISSUE TITLE
nbd-client: can't open '/dev/nbd0': Operation not permitted

### ISSUE THREAD

**Issue by jesta030** [javgh/sia-nbdserver#3]
I am trying to build a docker container from this and am pretty far along: I got sia-nbdserver running and listening on a unix socket. I am passing through /dev/nbd0 to the container but when I try to run `nbd-client -b 4096 -t 3600 /var/run/sia-nbdserver /dev/nbd0` it fails with `nbd-client: can't open '/dev/nbd0': Operation not permitted`. Any ideas why that is? I even did a `chmod 666 /dev/nbd0` hoping it's just a permission issue...

Edit: stupid me. passed through the whole device and it's solved. But now nbd-client throws an error "bad address" apparently it doesn't work with unix sockets.

**Comment by javgh** [comment]
Cool to see someone try to put this into a Docker container! I'm not sure I follow completely. You want to put everything into a single Docker container or just sia-nbdserver and then access it via nbd-client on the host? If it's the former, I don't think you need to pass through any devices, but my experience with Docker is limited.

Is this the exact command you are trying: `nbd-client -b 4096 -t 3600 /var/run/sia-nbdserver /dev/nbd0`? You need `-u` if you want nbd-client to use a unix domain socket.

You might also like to take a look at the `tcp` branch of this repo. There i modified the code to run via TCP instead. The documentation is not adjusted though. But you can set the server address via `-u`.

**Comment by javgh** [comment]
I guess I see want you mean by passing through the device. I suppose you would have to grant the Docker container access to the functionality of the `nbd` kernel module.

**Comment by javgh** [comment]
And you probably want to mount it on the host. Makes sense, I'm only slowly thinking through this. :smile:

**Comment by jesta030** [comment]
Yeah I'm also trying to wrap my head around what to mount where and how the data would flow...

The problem I had before was using alpine linux as the base image. It's implementation of nbd-client doesn't work with unix sockets, only tcp. I switched to debian as base image and that includes a version that does. Sadly the command `nbd-client -b 4096 -t 3600 -u /var/run/sia-nbdserver /dev/nbd0` (note I added the missing -u. :) ) now throws this error: 

`Couldn't resolve the nbd netlink family, make sure the nbd module is loaded and your nbd driver supports the netlink interface.`

Technically all modules loaded on the host are available inside docker containers... Maybe I created the socket at the wrong place? I have exactly zero experience with unix sockets...

Might give the tcp branch a try later if this doesn't get unstuck.

Edit: Think I got it. nbd-client needed another kernel module that my host kernel didn't have: netlink. Fortunately nbd-client comes with the option `-nonetlink`!

Now I got this: 
```
# nbd-client -b 4096 -t 3600 -u /tmp/sia-nbdserver /dev/nbd0 -nonetlink
Warning: the oldstyle protocol is no longer supported.
This method now uses the newstyle protocol with a default export
Negotiation: ..size = 1048576MB
bs=4096, sz=1099511627776 bytes
timeout=3600
#
```

Guess it's time to set up my renter and make a filesystem?

Edit2: I got it working.

- `nbd-client` connecting to socket
- in host os: `mkfs.xfs /dev/nbd0`, `mount -o sync /dev/nbd0 /data`, `touch /data/test_file`
- `ls -lh /root/.local/share/sia-nbdserver` inside container shows 13 files, one recently modified, containing test_file
- sia has 50 contracts but isn't uploading yet. I'll leave it over night and see what happened in the morning

**Comment by jesta030** [comment]
Closing this since I got TCP working.
